// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DBTesting.Models;

public partial class Department
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Employees> Employees { get; set; } = new List<Employees>();
}